zo_supervisor_monitor_start:
    path:     /monitor/start/{name}/{worker}
    defaults: { _controller: ZO\Bundle\SupervisorMonitorBundle\Controller\SecurityController::startAction }

zo_supervisor_monitor_restart:
    path:     /monitor/restart/{name}/{worker}
    defaults: { _controller: ZO\Bundle\SupervisorMonitorBundle\Controller\SecurityController::restartAction }

zo_supervisor_monitor_stop:
    path:     /monitor/stop/{name}/{worker}
    defaults: { _controller: ZO\Bundle\SupervisorMonitorBundle\Controller\SecurityController::stopAction }

zo_supervisor_monitor_clear_log:
    path:     /monitor/clear-log/{name}/{worker}
    defaults: { _controller: ZO\Bundle\SupervisorMonitorBundle\Controller\SecurityController::clearLogAction }


zo_supervisor_monitor_start_all:
    path:     /monitor/start-all/{name}
    defaults: { _controller: ZO\Bundle\SupervisorMonitorBundle\Controller\SecurityController::startAllAction }

zo_supervisor_monitor_restart_all:
    path:     /monitor/restart-all/{name}
    defaults: { _controller: ZO\Bundle\SupervisorMonitorBundle\Controller\SecurityController::restartAllAction }

zo_supervisor_monitor_stop_all:
    path:     /monitor/stop-all/{name}
    defaults: { _controller: ZO\Bundle\SupervisorMonitorBundle\Controller\SecurityController::stopAllAction }

zo_supervisor_monitor_index:
    path:     /monitor
    defaults: { _controller: ZO\Bundle\SupervisorMonitorBundle\Controller\SecurityController::indexAction }
