services:
    ZO\Bundle\SupervisorMonitorBundle\Controller\MonitorController:
        autowire: true
        autoconfigure: true
        public: true

    ZO\Bundle\SupervisorMonitorBundle\Util\SupervisorClient:
        autowire: true
        autoconfigure: true

